version: '2.3'

# if 'docker-compose run' is used
# do not forget '--service-ports'!

services:
    flower:
      image: herearii/deep-oc-flower
      ports:
        - 5000:5000
        - 6006:6006
      entrypoint: ["deepaas-run", "--listen-ip=0.0.0.0"]


    flower-gpu:
      image: herearii/deep-oc-flower:gpu
      runtime: nvidia
      ports:
        - 5000:5000
        - 6006:6006
      entrypoint: ["deepaas-run", "--listen-ip=0.0.0.0"]


    flower-rclone:
      extends:
        service: flower
      volumes:
        - $HOME/.config/rclone:/srv/.rclone
      environment:
        - RCLONE_CONFIG=/srv/.rclone/rclone.conf
